[package]
name = "valqeron-config"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
thiserror = { workspace = true }
directories = { workspace = true }

[lib]
name = "valqeron_config"

[lints]
workspace = true
